# Generated by Django 5.0.3 on 2024-03-11 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="author",
            table="auth_user",
        ),
    ]
