# Generated by Django 5.0.3 on 2024-03-11 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_author_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="author",
            table=None,
        ),
    ]
