# Generated by Django 5.0.3 on 2024-03-11 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_author_options_alter_author_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={"ordering": ("username",)},
        ),
    ]
